version: '3'

services:
  evidence-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "55018:8080"
    networks:
      evidence-frontend-network:
        ipv4_address: 172.20.253.17

networks:
  evidence-frontend-network:
    external: true
