version: '3'

services:
  evidence-webapp:
    container_name: evidence-webapp
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${WEBAPP_HOST_PORT}:8080"  # 55018
    networks:
      evidence-frontend-network:
        ipv4_address: 172.20.253.17
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        #window: 300s

networks:
  evidence-frontend-network:
    name: evidence-frontend-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.253.16/29
          ip_range: 172.20.253.20/30
