version: '3.7'

services:
  evidence-webapp:
    container_name: evidence-webapp
    build: 
      context: ${WEBAPP_PATH:-.}/
      dockerfile: Dockerfile
      args:
        VUE_APP_REST_PUBLIC_URL: ${REST_PUBLIC_URL}
        VUE_APP_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID:-}
    ports:
      - "${WEBAPP_HOSTPORT}:8080"  # 55018
    networks:
      evidence-network:
        ipv4_address: 172.20.253.1
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        #window: 300s
