<template>
  <h1 class="title is-3 is-spaced">BWS v4</h1>

  <h2 class="subtitle is-4">Compliance</h2>
  <div class="content">
    <p>
      The following settings are only applicable for the <b>interactive</b> Best-Worst Scaling UI v4.
      A subset of the sentence database is loaded into the Web App as <b>pool</b>.
      The sampling of BWS sets, and postprocessing of the evaluated BWS sets, the ML model training, and ML model prediction occurs in the Web App, i.e. on the user's device.

      <b>Data is only sent to servers if the user agreed to informed consent to contribute the data under a CC0 license (Public Domai)</b> so that the collected and postprocessed data can be published under a CC0 license (Public Domain) as well. "Data" are for example, evaluated BWS sets, clickstream data, log data, trained model weights, etc. 
      If the user does not consent with these terms, the user can still use the app for the intended purposes, i.e. rank and score sentences by individual preference, but these results are not stored persistently.
    </p>
  </div>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">

      <div class="field">
        <input id="interactivity-datalicense-toogle" class="switch is-rounded" type="checkbox"   
               v-model="hasConsented">
        <label for="interactivity-datalicense-toogle">
          I hereby grant a CC0 license (Public Domain) on all data generated by me using the Web App.
        </label>
      </div>

      <div class="field">
      </div>

    </div>
  </div>

  <h2 class="subtitle is-4">General Settings for the Interactive Bestworst UI</h2>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">

      <div class="field">
        <input id="interactivity-debug-toogle" class="switch is-rounded" type="checkbox"   
               v-model="debug">
        <label for="interactivity-debug-toogle">Print debugging information with "console.log"</label>
      </div>

      <div class="field">
      </div>

    </div>
  </div>

  <h2 class="subtitle is-4">Pool Size</h2>
  <div class="content">
    <p>
      The pool size of the locally stored sentences, feature vectors, annotation data, etc. must be constrained as end user devices have limited storage capacities.
    </p>
  </div>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">

      <div class="field">
        <label for="interactivity-min_pool_size">
          Minimum Pool Size
        </label>
        <input id="interactivity-min_pool_size" 
               class="slider has-output is-fullwidth is-primary is-circle is-medium" 
               type="range" v-model="min_pool_size" step="10" min="10" max="1000">
        <output for="interactivity-min_pool_size">{{ min_pool_size }}</output>
      </div>

      <div class="field">
        <label for="interactivity-max_pool_size">
          Maximum Pool Size
        </label>
        <input id="interactivity-max_pool_size" 
               class="slider has-output is-fullwidth is-primary is-circle is-medium" 
               type="range" v-model="max_pool_size" step="10" min="20" max="1000">
        <output for="interactivity-max_pool_size">{{ max_pool_size }}</output>
      </div>

    </div>
  </div>

  <h2 class="subtitle is-4">Only Load An Initial Pool Once</h2>
  <div class="content">
    <p>
      This option disable the automatic replenishment of the pool after examples were dropped.
      There are three scenarios.
      a) The pool never changes, i.e. no pool deletions, no pool additions.
      b) The pool shrinks, i.e. pool deletions but no pool additions.
      c) The pool renew itself, i.e. pool deletions and pool additions.
    </p>
  </div>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">
      <div class="field">
        <input id="interactivity-add-only-initially-toogle" 
               class="switch is-rounded" type="checkbox"   
               v-model="flagInitialLoadOnly">
        <label for="interactivity-add-only-initially-toogle">
          Only load an initial fixed pool / No pool additions lateron (Default: On)
        </label>
      </div>
    </div>
  </div>

  <h2 class="subtitle is-4">Drop and/or Add Examples by Training Score Distribution</h2>
  <div class="content">
    <p>
      In order to drop examples from the pool, or add new examples to the pool,
      a target training score distribution can be set 
      by specifying the bin edges and desired densities.
      If too many examples fall in a bin, equally the oldest and most coverged examples are removed from the pool.
      If too few examples fann in a bin, examples with a certain score range are queried from the database server and added to the pool.
    </p>
  </div>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">

      <div class="field">
        <input id="interactivity-drop-distribution-toogle" 
               class="switch is-rounded" type="checkbox"  
               v-model="flagDropDistribution">
        <label for="interactivity-drop-distribution-toogle">
          Drop examples from the pool by a target distribution (Default: Off)
        </label>
      </div>

      <div class="field">
        <input id="interactivity-add-distribution-toogle" 
               class="switch is-rounded" type="checkbox"  
               v-model="flagAddDistribution">
        <label for="interactivity-add-distribution-toogle">
          Add examples to the pool by a target distribution (Default: Off)
        </label>
      </div>

      <div class="field">
        <label for="interactivity-bin_edges">
          Bin Edges
        </label>
        <input id="interactivity-bin_edges" 
               class="input" type="text" v-model="bin_edges_text">
      </div>

      <div class="field">
        <label for="interactivity-target_probas">
          Target Densities for each bin
        </label>
        <input id="interactivity-target_probas" 
               class="input" type="text" v-model="target_probas_text">
      </div>

    </div>
  </div>

  <h2 class="subtitle is-4">Drop and/or Hide Examples if shown too often</h2>
  <div class="content">
    <p>
      We can specify a threshold of the maximum of times an examples is displayed to an user.
      On a first level, the example is <b>excluded from the BWS sampling process</b>, 
      i.e. the example remains in the pool but is not shown anymore -- 
      This option would prevent replenishing the pool automatically 
      (i.e. adding new examples from the database).
      The second option is to <b>remove the example from the pool</b> for good.
    </p>
  </div>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">

      <div class="field">
        <input id="interactivity-exclude-bwssampling-toogle" 
               class="switch is-rounded" type="checkbox"
               v-model="flagExcludeMaxDisplay">
        <label for="interactivity-exclude-bwssampling-toogle">
          Exclude from BWS sampling if shown too often (Default: On)
        </label>
      </div>

      <div class="field">
        <input id="interactivity-drop-display-toogle" 
               class="switch is-rounded" type="checkbox"  
               v-model="flagDropMaxDisplay">
        <label for="interactivity-drop-display-toogle">
          Drop examples from the pool if shown too often (Default: Off)
        </label>
      </div>

      <div class="field">
        <label for="interactivity-max_displays">
          Maximum number of times an sentence examples is shown to the user
        </label>
        <input id="interactivity-max_displays" 
               class="slider has-output is-fullwidth is-primary is-circle is-medium" 
               type="range" v-model="max_displays" step="1" min="1" max="30">
        <output for="interactivity-max_displays">{{ max_displays }}</output>
      </div>

    </div>
  </div>


  <h2 class="subtitle is-4">Drop Examples with Converged Model Scores</h2>
  <div class="content">
    <p>
      Ideally model scores converge for all examples.
      However, the model should converge to the correct scores.
      We could drop the examples from the pool if we suspect that the model is trapped in a local minima, i.e. we believe that most converged scores are wrong.
      Under normal circumstances, especially converged examples should remain within the pool.
    </p>
  </div>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">

      <div class="field">
        <input id="interactivity-drop-converge-toogle" 
               class="switch is-rounded" type="checkbox"
               v-model="flagDropConverge">
        <label for="interactivity-drop-converge-toogle">
          Drop examples from pool if model score converged (Default: Off)
        </label>
      </div>

      <div class="field">
        <label for="interactivity-eps_score_change">
          Termination criteria: Model score changes
        </label>
        <input id="interactivity-eps_score_change" 
               class="input" type="text" v-model="eps_score_change_text">
      </div>

    </div>
  </div>

  <h2 class="subtitle is-4">Drop Examples from Local Paired Comparison Matrix</h2>
  <div class="content">
    <p>
      When examples are dropped from the pool, 
      also delete the rows and columns of paired comparison matrix.
    </p>
  </div>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">
      <div class="field">
        <input id="interactivity-drop-pairs-toogle" 
               class="switch is-rounded" type="checkbox"   
               v-model="flagDropPairs">
        <label for="interactivity-drop-pairs-toogle">
          Drop examples from local pairs matrix
        </label>
      </div>
    </div>
  </div>


  <h2 class="subtitle is-4">Sample BWS sets from Local Pool</h2>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">

      <div class="field">
        <label for="interactivity-num_items_per_set">
          Number of items per BWS set (Default: 4)
        </label>
        <input id="interactivity-num_items_per_set" 
               class="slider has-output is-fullwidth is-primary is-circle is-medium" 
               type="range" v-model="num_items_per_set" step="1" min="3" max="5">
        <output for="interactivity-num_items_per_set">{{ num_items_per_set }}</output>
      </div>

      <div class="field">
        <label for="interactivity-num_preload_bwssets">
          Number of BWS sets to sample (to label before re-training)
        </label>
        <input id="interactivity-num_preload_bwssets" 
               class="slider has-output is-fullwidth is-primary is-circle is-medium" 
               type="range" v-model="num_preload_bwssets" step="1" min="1" max="20">
        <output for="interactivity-num_preload_bwssets">{{ num_preload_bwssets }}</output>
      </div>

      <div class="field">
        <div class="dropdown" id="interactivity-bws_sampling_method"
             v-on:click="showDropdownBwsSamplingMethod = !showDropdownBwsSamplingMethod"
             v-bind:class="{ 'is-active': showDropdownBwsSamplingMethod }">
          <div class="dropdown-trigger">
            <button class="button is-rounded is-light" type="button"
                    aria-haspopup="true" 
                    aria-controls="dropdown-bws_sampling_method">
              <span>
                <template v-if="bws_sampling_method == 'overlap'">overlap</template>
                <template v-if="bws_sampling_method == 'twice'">twice</template>
              </span>
              <span class="icon"><i class="fas fa-caret-down" aria-hidden="true"></i></span>
            </button>
          </div>
          <div class="dropdown-menu" id="dropdown-bws_sampling_method" role="menu">
            <div class="dropdown-content" v-on:click="bws_sampling_method = $event.target.id">
              <a id="overlap" class="dropdown-item">overlap</a>
              <a id="twice" class="dropdown-item">twice</a>
            </div>
          </div>
        </div>
        <label for="interactivity-bws_sampling_method">
          BWS sampling method
        </label>
      </div>

      <div class="field">
        <div class="dropdown" id="interactivity-item_sampling_method" 
             v-on:click="showDropdownItemSamplingMethod = !showDropdownItemSamplingMethod"
             v-bind:class="{ 'is-active': showDropdownItemSamplingMethod }">
          <div class="dropdown-trigger">
            <button class="button is-rounded is-light" type="button"
                    aria-haspopup="true" 
                    aria-controls="dropdown-item_sampling_method">
              <span>
                <template v-if="item_sampling_method == 'random'">random</template>
                <template v-if="item_sampling_method == 'exploit'">exploit</template>
                <template v-if="item_sampling_method == 'newer-unstable'">newer-unstable</template>
              </span>
              <span class="icon"><i class="fas fa-caret-down" aria-hidden="true"></i></span>
            </button>
          </div>
          <div class="dropdown-menu" id="dropdown-item_sampling_method" role="menu">
            <div class="dropdown-content" v-on:click="item_sampling_method = $event.target.id">
              <a id="random" class="dropdown-item">random</a>
              <a id="exploit" class="dropdown-item">exploit</a>
              <a id="newer-unstable" class="dropdown-item">newer-unstable</a>
            </div>
          </div>
        </div>
        <label for="interactivity-item_sampling_method">
          Sampling example items 
        </label>
      </div>

    </div>
  </div>

  <h2 class="subtitle is-4">Count Pairs and Update Training Scores</h2>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">
      <div class="field">
      </div>
      <div class="field">
      </div>
    </div>
  </div>

  <h2 class="subtitle is-4">Train Local ML Model</h2>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">
      <div class="field">
      </div>
      <div class="field">
      </div>
    </div>
  </div>

</template>


<script>
import { useI18n } from 'vue-i18n';
import { defineComponent, watch, ref } from 'vue';
import { useInteractivity } from '@/components/bestworst/interactivity.js';
import { useInteractivitySettings } from '@/components/bestworst/interactivity-settings.js';

export default defineComponent({
  name: "InteractivitySettings",

  setup(){
    // i18n data
    const { t } = useI18n();

    // Dropdown menus
    const showDropdownItemSamplingMethod = ref(false);
    const showDropdownBwsSamplingMethod = ref(false);

    // Settings for bestworst v4 (interactivity)
    const { 
      hasConsented, debug,
    } = useInteractivity();

    const {
      // Settings for (1) and (2)
      flagInitialLoadOnly,
      min_pool_size, max_pool_size,
      flagDropDistribution, flagAddDistribution, bin_edges, target_probas, 
      // Settings for (1) and (3)
      flagDropMaxDisplay, flagExcludeMaxDisplay, max_displays, 
      // Settings for (1)
      flagDropConverge, eps_score_change,
      flagDropPairs,
      // Settings for (3)
      num_items_per_set, num_preload_bwssets, 
        bws_sampling_method, item_sampling_method,
    } = useInteractivitySettings();

    watch(min_pool_size, (minsz) => {
      max_pool_size.value = (max_pool_size.value <= parseInt(minsz)) ? (parseInt(minsz) + 1) : max_pool_size.value
    });
    watch(max_pool_size, (maxsz) => {
      min_pool_size.value = (min_pool_size.value >= parseInt(maxsz)) ? (parseInt(maxsz) - 1) : min_pool_size.value
    })

    const bin_edges_text = ref(bin_edges.value.join());
    watch(bin_edges_text, (txt) => {
      bin_edges.value = txt.split(",").map(e => Number(e)).sort();
      // nconsole.log(bin_edges.value)
    });

    const target_probas_text = ref(target_probas.value.join(","));
    watch(target_probas_text, (txt) => {
      target_probas.value = txt.split(",").map(e => Number(e)).sort();
      //console.log(target_probas.value)
    });

    const eps_score_change_text = ref(
      Number.parseFloat(eps_score_change.value).toExponential(1))
    watch(eps_score_change_text, (txt) => {
      eps_score_change.value = Number.parseFloat(txt);
    });


    return { 
      t,
      hasConsented, debug,
      min_pool_size, max_pool_size, 
        flagInitialLoadOnly,
        flagDropDistribution, flagAddDistribution, bin_edges_text, target_probas_text, 
        flagExcludeMaxDisplay, flagDropMaxDisplay, max_displays, 
        flagDropConverge, eps_score_change_text,
        flagDropPairs,
      num_items_per_set, num_preload_bwssets, bws_sampling_method, item_sampling_method,
        showDropdownItemSamplingMethod, showDropdownBwsSamplingMethod
    }
  }
});
</script>

