<template>
  <h1 class="title is-3 is-spaced">{{ t('settings.general') }}</h1>

  <h2 class="subtitle is-4">{{ t('settings.appearance') }}</h2>
  <div class="field">
    <input id="darkmode-toogle" class="switch is-rounded" type="checkbox"   
           v-model="darkmodetheme">
    <label for="darkmode-toogle">Darkmode</label>
  </div>

  <h2 class="subtitle is-4">{{ t('settings.language') }}</h2>
  <div class="field">
    <LanguageSwitcher />
  </div>

  <h2 class="subtitle is-4">Debugging Verbosity</h2>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">
      <div class="field">
        <input id="interactivity-debugVerbose-toogle" class="switch is-rounded" type="checkbox"   
               v-model="debugVerbose">
        <label for="interactivity-debugVerbose-toogle">Print debugging information with "console.log"</label>
      </div>
    </div>
  </div>


	<h1 class="title is-3 is-spaced">Legal and Compliance</h1>

  <h2 class="subtitle is-4">Data Donation</h2>
  <div class="content">
    <p>
      The following settings are only applicable for the <b>interactive</b> Best-Worst Scaling UI v4.
      A subset of the sentence database is loaded into the Web App as <b>pool</b>.
      The sampling of BWS sets, and postprocessing of the evaluated BWS sets, the ML model training, and ML model prediction occurs in the Web App, i.e. on the user's device.

      <b>Data is only sent to servers if the user agreed to informed consent to contribute the data under a CC0 license (Public Domai)</b> so that the collected and postprocessed data can be published under a CC0 license (Public Domain) as well. "Data" are for example, evaluated BWS sets, clickstream data, log data, trained model weights, etc. 
      If the user does not consent with these terms, the user can still use the app for the intended purposes, i.e. rank and score sentences by individual preference, but these results are not stored persistently.
    </p>
  </div>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">

      <div class="field">
        <input id="interactivity-datalicense-toogle" class="switch is-rounded" type="checkbox"   
               v-model="hasDataDonationConsent">
        <label for="interactivity-datalicense-toogle">
          I hereby grant a CC0 license (Public Domain) on all data generated by me using the Web App.
        </label>
      </div>
    </div>
  </div>

</template>


<script>
import { defineComponent } from "vue";
import { useI18n } from 'vue-i18n';
import { useDarkmodeToggle } from '@/components/settings/darkmode-toggle.js';
import { useGeneralSettings } from '@/components/settings/general-settings.js';
import LanguageSwitcher from "@/components/layout/LanguageSwitcher.vue";


export default defineComponent({
  name: "Settings",

  components: {
    LanguageSwitcher
  },

  setup(){
    const { t } = useI18n();

		// Load General Settings
		const { hasDataDonationConsent, debugVerbose, loadGeneralSettings } = useGeneralSettings();
		loadGeneralSettings();

    // this also adds an watcher
    const { darkmodetheme } = useDarkmodeToggle();
    
    return { 
      t,
      darkmodetheme,
			hasDataDonationConsent, 
			debugVerbose
    }
  },
});
</script>
