<template>
  <h1 class="title is-3 is-spaced">Legal Compliance</h1>  <!-- Rechtskonformität -->

  <h2 class="subtitle is-4">Data Donation</h2>  <!-- Datenspende -->
  <div class="content">
    <p v-if="language == 'de'">
      In der App werden die Präferenzen, Entscheidungen und Nutzungsverhalten der Benutzer aufgezeichnet, aber nur dann Daten an die Server gesendet, gespeichert, weiter verarbeitet, und veröffentlicht, wenn der Benutzer eine CC0-Lizenz auf die von ihm erzeugten Daten erteilt hat.
    </p>
    <p v-else>
      In the app, the preferences, decisions and usage behavior of the users are recorded, but data is only sent to the server, stored, processed, and published if the user has granted a CC0 license to the data generated by him.
    </p>
  </div>
  <div class="columns">
    <div class="column is-narrow-tablet is-narrow-desktop is-narrow-widescreen is-narrow-fullhd">

      <div class="field">
        <input id="interactivity-datalicense-toogle" class="switch is-rounded" type="checkbox"   
               v-model="has_data_donation_consent">
        <label for="interactivity-datalicense-toogle">
          <template v-if="language == 'de'">
            Hiermit erteile ich eine CC0-Lizenz auf alle von mir mit der Web-App erzeugten Daten.
          </template>
          <template v-else>
            I hereby grant a CC0 license on all data generated by me using the Web App.
          </template>
        </label>
      </div>
    </div>
  </div>

</template>


<script>
import { defineComponent } from "vue";
import { useI18n } from 'vue-i18n';
import { useGeneralSettings } from '@/components/settings/general-settings.js';


export default defineComponent({
  name: "Settings",

  components: {},

  setup(){
    const { t } = useI18n();

		// Load General Settings
		const { 
      language, 
      has_data_donation_consent, 
      loadGeneralSettings 
    } = useGeneralSettings();
		loadGeneralSettings();

    return { 
      t, 
      language,
			has_data_donation_consent
    }
  },
});
</script>
